import { Inter } from 'next/font/google'
import './globals.css'
import Header from '../../components/Header'
import Link from 'next/link'
import styles from './styles.module.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'song portfolio',
  description: 'Generated by song',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{backgroundImage: 'url(/img/bg.jpg)', backgroundSize: 'cover', backgroundPosition: 'center'}}>
      <Header></Header>
      <ol style={{ display: 'flex', flexDirection: 'row', justifyContent: 'center', gap: '40px',marginTop:'100px',marginBottom:'30px'}}>
        <li style={{ fontSize: '35px', marginLeft: '40px' }}><Link href='/clerk-auth'><span className={styles.link}>Clerk-auth</span></Link></li>
        <li style={{ fontSize: '35px' }}><Link href='/counter'><span className={styles.link}>Counter</span></Link></li>
        <li style={{ fontSize: '35px' }}><Link href='/opencontact-book'><span className={styles.link}>Opencontact-book</span></Link></li>
        <li style={{ fontSize: '35px' }}><Link href='/token-drop'><span className={styles.link}>Token-drop</span></Link></li>
        <li style={{ fontSize: '35px' }}><Link href='/rc721-nft-drop'><span className={styles.link}>Rc721-nft-drop</span></Link></li>
        <li style={{ fontSize: '35px' }}><Link href='/Market-place'><span className={styles.link}>Market-place</span></Link></li>
      </ol>
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100%' }}>
        {children}
      </div>
      </body>
    </html>
  )
}
